require('./teste');
require('./usuarios');
require('./criacaoDatabase');
require('./insert');
require('./produto');
require('./cliente');
require('./pedido');
require('./FinalizarCompra');
require('./carrinho');